### ISSUE TITLE
Can't compile from Pypi's SDIST

### ISSUE THREAD

**Issue by onkelbeh** [ctalkington/python-directv#60]
Hi Chris,

me again, I hope you don't mind if I use your component for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).

In addition to the version deadlocks Martin already mentioned, I just saw that your SDIST archive on Pypi is incomplete.

```
python3.8 setup.py build -j 10
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    install_requires=list(val.strip() for val in open("requirements.txt")),
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/directv-0.3.0::HomeAssistantRepository failed (compile phase):
 *   (no error message)
```

Fixed it for me with https://github.com/onkelbeh/HomeAssistantRepository/commit/5547955ca0d09c0a37da7911849e81bee94d32af, though it's currently (-0.3.0) not usable due to the already mentioned version lockouts. Also I do not understand why you use different names for the package on Pypi and Github.

Thanks a lot.

**Comment by ctalkington** [comment]
requirements will be included in 0.4.0 along with Martins pinning fixes
